### ISSUE TITLE
 cannot convert argument 1 from 'k4a::image' to 'k4a::image &'

### ISSUE THREAD

**Issue by limgm** [UnaNancyOwen/AzureKinectSample#1]
Thank you for the great sample code again!

When I tried to copy the source files for the cpp/color example and build on my own visual studio project, I got the error on util.h file line 114
`
'cv::Mat k4a::get_mat(k4a::image &,bool)': cannot convert argument 1 from 'k4a::image' to 'k4a::image &'
`

So I edit line 40 in util.h file
`
cv::Mat get_mat( k4a::image& src, bool deep_copy = true )
`
to the below line by removing `&` then it is able to compile successfully (is there anything wrong with my setup?)
`
cv::Mat get_mat( k4a::image src, bool deep_copy = true )
`

**Comment by UnaNancyOwen** [comment]
I think it is good to passed by reference, because it is faster than passed by value.

> I got the error on util.h file line 114

Why does that error occur in [util.h#L114](https://github.com/UnaNancyOwen/AzureKinectSample/blob/master/sample/cpp/color/util.h#L114)?
In the C++ samples doesn't use k4a_get_mat() function.
If you are using [cpp/color](https://github.com/UnaNancyOwen/AzureKinectSample/blob/master/sample/cpp/color), It is unnatural to get an error that line.

> is there anything wrong with my setup?

I recommend generating project using CMake.
